version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
workflows:
  build_and_test:
    jobs:
      - cypress/install:
          name: Build Vue app
          build: "npm run build"
      - cypress/run:
          name: Test on Chrome 73
          requires:
            - cypress/install
          executor: "cypress/browsers-chrome73-ff68"
          browser: chrome
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          record: true
      - cypress/run:
          name: Test on Firefox 68
          requires:
            - cypress/install
          executor: "cypress/browsers-chrome73-ff68"
          browser: firefox
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          record: true

