version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
workflows:
  build:
    jobs:
      - cypress/run:
          build: "yarn"
          start: "yarn serve"
          wait-on: 'http://localhost:8080'
          record: true
