version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: Test on Chrome 73
          executor: "browsers-chrome73-ff68"
          browser: chrome
          build: npm run build
          start: "npm run serve"
          wait-on: 'http://localhost:8080'
          record: true
          filters:
            branches:
            pull_request: true
